// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)


import PriceController from "./price_controller"
application.register("price", PriceController)

import ReviewController from "./review_controller"
application.register("review", ReviewController)


import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
